apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - name: mypd
        mountPath: /app/data
  volumes:
    - name: mypd
      hostPath: 
        path: /mnt/d/host-data
        type: Directory
#      persistentVolumeClaim:
#        claimName: pvc-hostpath


