---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "we"    
  hostPath:
    path: /mnt/d/host-data
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "we"    
  resources:
    requests:
      storage: 1Gi
          
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - name: mypd
        mountPath: /app/data
  volumes:
    - name: mypd
#      hostPath:
#        path: /mnt/d/host-data
#        type: Directory
      persistentVolumeClaim:
        claimName: pvc-hostpath

---
